INSERT ALL
    WHEN VALOR2 = 'ACTIVIDAD' THEN
        INTO T_ACTIVIDAD (DESCRIPCION, HS_MIN_ASIGNADAS) VALUES (DESCRIPCION, VALOR1)
    WHEN VALOR2 = 'MARCA'  THEN
        INTO L_MARCA (DESCRIPCION) VALUES (DESCRIPCION)
    WHEN VALOR2 = 'BARRIO'  THEN
        INTO G_BARRIO (NOMBRE, CANT_HABITANTES) VALUES (DESCRIPCION, VALOR1)
    WHEN VALOR2 = 'MOTIVO'  THEN
        INTO G_MOTIVO (DESCRIPCION, ESTADO) VALUES (DESCRIPCION, VALOR1)
SELECT DESCRIPCION, VALOR1, VALOR2 FROM G_MIGRACION;
