
ALTER TABLE F_REDONDO ADD CHECK CONSTRAINT CHK_COMPLETADO
CHECK CONSTRAINT  CHECK (COMPLETADO = 'N' AND ID_MOTIVO NOT NULL);


ALTER TABLE F_REDONDO
ADD CONSTRAINT CHK_COMPLETADO CHECK (COMPLETADO = 'N' AND ID_MOTIVO NOT NULL);

ALTER TABLE F_REDONDO
ADD CONSTRAINT CHK_HORA_SALIDA check (substr(HORA_SALIDA, 3,1) = ':' AND substr(HORA_SALIDA, 6,1) = ':');

ALTER TABLE F_REDONDO
ADD CONSTRAINT CHK_HORA_LLEGADA check (substr(HORA_LLEGADA, 3,1) = ':' AND substr(HORA_LLEGADA, 6,1) = ':');

