CREATE OR REPLACE TRIGGER
T_DECLARACION_DETALLE
BEFORE INSERT OR DELETE OR UPDATE
ON DECLARACIÓN_DETALLE
FOR EACH ROW
DECLARE
V_COD_CATEGORIA_CONTRIB CATEGORIA.COD_CATEGORIA%TYPE;
V_MONTO_APLICABLE NUMBER(9);
BEGIN
    IF INSERTING THEN
        SELECT c.COD_CATEGORIA INTO V_COD_CATEGORIA_CONTRIB
        FROM DECLARACION d
        JOIN CONTRIBUYENTE c ON d.RUC = c.RUC;
        WHERE d.ID = :new.ID;

        IF V_COD_CATEGORIA_CONTRIB <> :new.COD_CATEGORIA THEN
            RAISE_APPLICATION_ERROR(-20000, 'CATEGORIA NO CORRESPONDE A CONTRIBUYENTE.');
        END IF;

        SELECT ROUND(:new.MONTO_PERIODO * cd.PORCENTAJE/100)
        INTO :new.V_MONTO_APLICABLE
        FROM CONCEPTO_A_DECLARAR cd 
        WHERE cd.COD_CATEGORIA = :new.COD_CATEGORIA
            AND cd.COD_IMPUESTO = :new.COD_IMPUESTO;
    END;
    IF DELETING OR UPDATING THEN
        RAISE_APPLICATION_ERROR(-20000, 'NO SE PERMITE MODIFICAR');
    END IF;
END;