CREATE OR REPLACE PROCEDURE P_RENOMBRAR IS
CURSOR C_TABLAS IS 
    SELECT DISTINCT(TABLE_NAME) AS NOMBRE_TABLA
    FROM USER_TAB_COLUMNS 
    WHERE UPPER(COLUMN_NAME) LIKE 'CEDULA' AND
    UPPER(TABLE_NAME) NOT LIKE 'B_%';
    V_SENTENCIA_ALTER VARCHAR2(500);
BEGIN
    FOR TAB IN C_TABLAS LOOP
        V_SENTENCIA_ALTER := 'ALTER TABLE ' || TAB.NOMBRE_TABLA || ' RENAME COLUMN CEDULA TO UIP';
        EXECUTE IMMEDIATE RTRIM(V_SENTENCIA_ALTER);
    END LOOP;
END;