
CREATE TABLE ACTIVIDAD (
       COD_ACTIVIDAD        NUMBER NOT NULL,
       RUC                  VARCHAR2(11) NOT NULL,
       CONSTRAINT PKACTIVIDAD 
              PRIMARY KEY (COD_ACTIVIDAD, RUC)
);


CREATE TABLE CATEGORIA (
       NOMBRE_CATEGORIA     VARCHAR2(60) NOT NULL,
       COD_CATEGORIA        NUMBER(2) NOT NULL,
       CONSTRAINT PKCATEGORIA 
              PRIMARY KEY (COD_CATEGORIA)
);


CREATE TABLE CONCEPTO_A_DECLARAR (
       COD_CATEGORIA        NUMBER(2) NOT NULL,
       COD_IMPUESTO         NUMBER(3) NOT NULL,
       CONCEPTO             NUMBER(4) NOT NULL,
       NOMBRE_CONCEPTO      VARCHAR2(10) NOT NULL,
       DESCRIPCION_CONCEPTO VARCHAR2(500) NOT NULL,
       PORCENTAJE           NUMBER(2) DEFAULT 0 NOT NULL,
       DEBITO_CREDITO       VARCHAR2(1) DEFAULT 'D' NOT NULL
                                   CONSTRAINT CHK_DEB_CRED11
                                          CHECK (DEBITO_CREDITO IN ('D', 'C')),
       CONSTRAINT PKCONCEPTO_A_DECLARAR 
              PRIMARY KEY (COD_CATEGORIA, COD_IMPUESTO)
);


CREATE TABLE CONTRIBUYENTE (
       NOMBRE               VARCHAR2(50) NOT NULL,
       COD_CATEGORIA        NUMBER(2) NOT NULL,
       TIPO_CONTRIB         VARCHAR2(1) DEFAULT 'F' NOT NULL
                                   CONSTRAINT FISICO_JURIDICO11
                                          CHECK (TIPO_CONTRIB IN ('F', 'J')),
       APELLIDO_RAZON       VARCHAR2(50) NOT NULL,
       DIRECCION            VARCHAR2(100) NOT NULL,
       CEDULA               VARCHAR2(10) NULL,
       DIA_DECLARACION      NUMBER(2) NOT NULL,
       HABILITADO           VARCHAR2(1) DEFAULT 'S' NOT NULL
                                   CONSTRAINT CHK_SI_NO11
                                          CHECK (HABILITADO IN ('S', 'N')),
       FECHA_VALIDEZ        DATE NULL,
       RUC                  VARCHAR2(11) NOT NULL,
       CONSTRAINT PKCONTRIBUYENTE 
              PRIMARY KEY (RUC)
);


CREATE TABLE DECLARACION (
       FECHA_PRESENTACION   DATE NULL,
       PERIODO_ANIO         NUMBER(4) NOT NULL,
       PERIODO_MES          NUMBER(2) DEFAULT 0 NOT NULL,
       RUC                  VARCHAR2(11) NULL,
       MONTO_A_PAGAR        NUMBER(9) NULL,
       ID                   NUMBER NOT NULL,
       CONSTRAINT PKDECLARACION 
              PRIMARY KEY (ID)
);


CREATE TABLE DECLARACION_DETALLE (
       COD_CATEGORIA        NUMBER(2) NOT NULL,
       ID                   NUMBER NOT NULL,
       COD_IMPUESTO         NUMBER(3) NOT NULL,
       MONTO_PERIODO        NUMBER(9) DEFAULT 0 NOT NULL,
       MONTO_APLICABLE      NUMBER(9) DEFAULT 0 NOT NULL,
       CONSTRAINT PKDECLARACION_DETA 
              PRIMARY KEY (COD_CATEGORIA, ID, COD_IMPUESTO)
);


CREATE TABLE PAGOS (
       FECHA_PAGO           DATE NOT NULL,
       MONTO_PAGO           NUMBER(9) DEFAULT 0 NOT NULL,
       ID                   NUMBER NOT NULL,
       ID_DECLARACION       NUMBER NOT NULL,
       CONSTRAINT PKPAGOS 
              PRIMARY KEY (ID)
);


CREATE TABLE RUBRO_ACTIVIDAD (
       DESCRIPCION_ACTIVIDAD VARCHAR2(100) NOT NULL,
       COD_ACTIVIDAD        NUMBER NOT NULL,
       CONSTRAINT PKRUBRO_ACTIVIDAD 
              PRIMARY KEY (COD_ACTIVIDAD)
);


CREATE TABLE TIPOS_IMPUESTOS (
       NOMBRE_IMPUESTO      VARCHAR2(60) NOT NULL,
       PORCENTAJE           NUMBER(2) DEFAULT 0 NOT NULL,
       COD_IMPUESTO         NUMBER(3) NOT NULL,
       CONSTRAINT PKTIPOS_IMPUESTOS 
              PRIMARY KEY (COD_IMPUESTO)
);


ALTER TABLE ACTIVIDAD
       ADD  ( CONSTRAINT R_CONTRIB_ACTIVID
              FOREIGN KEY (RUC)
                             REFERENCES CONTRIBUYENTE ) ;


ALTER TABLE ACTIVIDAD
       ADD  ( CONSTRAINT R_ACTIVID_CONTRIB
              FOREIGN KEY (COD_ACTIVIDAD)
                             REFERENCES RUBRO_ACTIVIDAD ) ;


ALTER TABLE CONCEPTO_A_DECLARAR
       ADD  ( CONSTRAINT R_TIPOS_CONCEPTO
              FOREIGN KEY (COD_IMPUESTO)
                             REFERENCES TIPOS_IMPUESTOS ) ;


ALTER TABLE CONCEPTO_A_DECLARAR
       ADD  ( CONSTRAINT R_CATEGORIA_CONCEPTO
              FOREIGN KEY (COD_CATEGORIA)
                             REFERENCES CATEGORIA ) ;


ALTER TABLE CONTRIBUYENTE
       ADD  ( CONSTRAINT R_CATEGORIA_CONTRIB
              FOREIGN KEY (COD_CATEGORIA)
                             REFERENCES CATEGORIA ) ;


ALTER TABLE DECLARACION
       ADD  ( CONSTRAINT R_CONTRI_DECLA
              FOREIGN KEY (RUC)
                             REFERENCES CONTRIBUYENTE ) ;


ALTER TABLE DECLARACION_DETALLE
       ADD  ( CONSTRAINT R_DECLA_DETALLE
              FOREIGN KEY (ID)
                             REFERENCES DECLARACION ) ;


ALTER TABLE DECLARACION_DETALLE
       ADD  ( CONSTRAINT R_CONCEPTO_DECLA
              FOREIGN KEY (COD_CATEGORIA, COD_IMPUESTO)
                             REFERENCES CONCEPTO_A_DECLARAR ) ;


ALTER TABLE PAGOS
       ADD  ( CONSTRAINT R_DECLA_PAGOS
              FOREIGN KEY (ID_DECLARACION)
                             REFERENCES DECLARACION ) ;

