
CREATE TABLE CATEGORIAS
(
	COD_CATEGORIA        NUMBER(8) NOT NULL ,
	NOMBRE_CATEGORIA     VARCHAR2(30) NOT NULL ,
	ASIGNACION           NUMBER(8) NOT NULL ,
CONSTRAINT  PKCATEGORIAS PRIMARY KEY (COD_CATEGORIA)
);

CREATE TABLE EMPLEADOS
(
	CEDULA               NUMBER(11) NOT NULL ,
	NOMBRE               VARCHAR2(30) NOT NULL ,
	APELLIDO             VARCHAR2(30) NOT NULL ,
	FECHA_ING            DATE NOT NULL ,
	FECHA_NACIM          DATE NOT NULL ,
	TELEFONO             VARCHAR2(100) NOT NULL ,
	DIRECCION            VARCHAR2(60) NOT NULL ,
	BARRIO               VARCHAR2(100) NOT NULL ,
	LOCALIDAD            VARCHAR2(100) NOT NULL ,
CONSTRAINT  PKEMPLEADOS_S2 PRIMARY KEY (CEDULA)
);

CREATE TABLE FERIADOS
(
	DIA_FERIADO          DATE NOT NULL ,
	MOTIVO               VARCHAR2(20) NOT NULL ,
CONSTRAINT  XPKFERIADOS PRIMARY KEY (DIA_FERIADO)
);

CREATE TABLE INSTITUCION
(
	COD_INSTITUCION      NUMBER(8) NOT NULL ,
	NOMBRE_INSTITUCION   VARCHAR2(60) NULL ,
CONSTRAINT  PKINSTITUCION PRIMARY KEY (COD_INSTITUCION)
);

CREATE TABLE CARGOS
(
	ID_CARGO             NUMBER(12) NOT NULL ,
	COD_CATEGORIA        NUMBER(8) NOT NULL ,
	CEDULA               NUMBER(11) NOT NULL ,
	COD_INSTITUCION      NUMBER(8) NOT NULL ,
	FECHA_NOMBRAMIENTO   DATE NOT NULL ,
	RESOLUCION_LEGAL     VARCHAR2(20) NOT NULL ,
	FECHA_BAJA           DATE NULL ,
CONSTRAINT  PKCARGOS PRIMARY KEY (ID_CARGO)
);

CREATE TABLE PERMISOS
(
	ID_PERMISO           NUMBER(12) NOT NULL ,
	MOTIVO               VARCHAR2(20) NOT NULL ,
	FECHA_INI            DATE NOT NULL ,
	DIAS_PERMISO         NUMBER(2) NOT NULL ,
	FECHA_FIN            DATE NULL ,
	CEDULA               NUMBER(11) NULL ,
CONSTRAINT  PKPERMISOS PRIMARY KEY (ID_PERMISO)
);

CREATE TABLE REGISTRO_DE_ABOGADOS
(
	CEDULA               NUMBER(11) NOT NULL ,
	NRO_REGISTRO         NUMBER(4) NOT NULL ,
	FECHA_REGISTRO       DATE NOT NULL ,
	FECHA_BAJA           DATE NULL ,
CONSTRAINT  PKREGISTRO_DE_JUECES PRIMARY KEY (CEDULA)
);

CREATE TABLE SUMARIO
(
	ID_SUMARIO           NUMBER(8) NOT NULL ,
	COD_INSTITUCION      NUMBER(8) NOT NULL ,
	RESOLUCION_LEGAL     VARCHAR2(20) NULL ,
	FECHA_REGISTRO       DATE NOT NULL ,
	FECHA_INICIO_EFECTIVO DATE NOT NULL ,
	FECHA_LIMITE         DATE NOT NULL ,
	FECHA_FIN            DATE NULL ,
CONSTRAINT  PKSUMARIO PRIMARY KEY (ID_SUMARIO)
);

CREATE TABLE JUECES
(
	CEDULA               NUMBER(11) NOT NULL ,
	ID_SUMARIO           NUMBER(8) NOT NULL ,
	TITULAR_SUPLENTE     VARCHAR2(2) DEFAULT  'TI'  NOT NULL  CONSTRAINT  CHK_TIT CHECK (TITULAR_SUPLENTE IN('TI','S1','S2')),
CONSTRAINT  PKJUECES PRIMARY KEY (CEDULA,ID_SUMARIO)
);

CREATE TABLE SEGUIMIENTO
(
	ID_SEGUIMIENTO       NUMBER(12) NOT NULL ,
	ID_SUMARIO           NUMBER(8) NULL ,
	FECHA_EVENTO         DATE NOT NULL ,
	DESCRIPCION          VARCHAR2(4000) NULL ,
CONSTRAINT  PKSEGUIMIENTO PRIMARY KEY (ID_SEGUIMIENTO)
);

CREATE TABLE SUMARIADOS
(
	ID_SUMARIO           NUMBER(8) NOT NULL ,
	CEDULA               NUMBER(11) NOT NULL ,
	MOTIVO_SUMARIO       VARCHAR2(4000) NOT NULL ,
CONSTRAINT  PKSUMARIADOS PRIMARY KEY (ID_SUMARIO,CEDULA)
);

ALTER TABLE CARGOS
	ADD (CONSTRAINT R_INST_CARGO FOREIGN KEY (COD_INSTITUCION) REFERENCES INSTITUCION (COD_INSTITUCION));

ALTER TABLE CARGOS
	ADD (CONSTRAINT R_EMP_CARGO FOREIGN KEY (CEDULA) REFERENCES EMPLEADOS (CEDULA));

ALTER TABLE CARGOS
	ADD (CONSTRAINT R_CAT_CAR FOREIGN KEY (COD_CATEGORIA) REFERENCES CATEGORIAS (COD_CATEGORIA));

ALTER TABLE PERMISOS
	ADD (CONSTRAINT R_CED_PERMISO FOREIGN KEY (CEDULA) REFERENCES EMPLEADOS (CEDULA));

ALTER TABLE REGISTRO_DE_ABOGADOS
	ADD (CONSTRAINT R_EMP_REG FOREIGN KEY (CEDULA) REFERENCES EMPLEADOS (CEDULA));

ALTER TABLE SUMARIO
	ADD (CONSTRAINT R_INS_SUM FOREIGN KEY (COD_INSTITUCION) REFERENCES INSTITUCION (COD_INSTITUCION));

ALTER TABLE JUECES
	ADD (CONSTRAINT R_REG_JUECES FOREIGN KEY (CEDULA) REFERENCES REGISTRO_DE_ABOGADOS (CEDULA));

ALTER TABLE JUECES
	ADD (CONSTRAINT R_SUMA_JUECES FOREIGN KEY (ID_SUMARIO) REFERENCES SUMARIO (ID_SUMARIO));

ALTER TABLE SEGUIMIENTO
	ADD (CONSTRAINT R_SUM_SEGUI FOREIGN KEY (ID_SUMARIO) REFERENCES SUMARIO (ID_SUMARIO));

ALTER TABLE SUMARIADOS
	ADD (CONSTRAINT R_SUM_EMP FOREIGN KEY (ID_SUMARIO) REFERENCES SUMARIO (ID_SUMARIO));

ALTER TABLE SUMARIADOS
	ADD (CONSTRAINT R_EMP_SUM FOREIGN KEY (CEDULA) REFERENCES EMPLEADOS (CEDULA));
