CREATE TABLE G_MIGRACION(
DESCRIPCION VARCHAR2(2000),
VALOR1 VARCHAR2(500),
VALOR2 VARCHAR2(500)
)TABLESPACE BASED2TP;
insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('VOLVO', null, 'MARCA');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('MERCEDES BENZ', null, 'MARCA');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('LAS MERCEDES', '150', 'BARRIO');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('MBOCAYATY', '758', 'BARRIO');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('PATINHO', '256', 'BARRIO');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('SANTA LUCIA', '1023', 'BARRIO');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('AGUAPEY', '635', 'BARRIO');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('PITIANTUTA', '1850', 'BARRIO');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('LAGUNA GRANDE', '980', 'BARRIO');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('ESTANZUELA', '324', 'BARRIO');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('VALLE YBATE', '157', 'BARRIO');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('MBURICAO', '365', 'BARRIO');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('MANORA', '859', 'BARRIO');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('SAN VICENTE', '745', 'BARRIO');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('NAZARETH', '1300', 'BARRIO');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('DESPERFECTO MECANICO', 'A', 'MOTIVO');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('ACCIDENTE DE TRANSITO', 'A', 'MOTIVO');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('INCENDIO DEL BUS', 'A', 'MOTIVO');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('PINOZA', '1589', 'BARRIO');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('HERRERA', '623', 'BARRIO');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('HIPODROMO', '748', 'BARRIO');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('PIQUETE CUE', '958', 'BARRIO');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('VILLA MADRIR', '421', 'BARRIO');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('RETENIDO POR PMT', 'A', 'MOTIVO');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('ASALTO', 'A', 'MOTIVO');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('RETENIDO POR PC', 'A', 'MOTIVO');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('REVISAR LA PRESIÓN DEL AIRE Y EL ESTADO DE LAS LLANTAS.', '2', 'ACTIVIDAD');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('ALINEAR LAS LLANTAS.', '1.5', 'ACTIVIDAD');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('INSPECCIONAR Y CALIBRAR LOS FRENOS', '1.0', 'ACTIVIDAD');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('REVISAR LA BATERÍA Y LOS SISTEMAS ELÉCTRICOS DEL VEHÍCULO.', '0.5', 'ACTIVIDAD');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('LIMPIAR Y LUBRICAR LAS PARTES DEL MOTOR', '3.5', 'ACTIVIDAD');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('DESMONTAR LAS PIEZAS DEL MOTOR PARA DETECTAR DÓNDE ESTÁ LA AVERÍA', '4', 'ACTIVIDAD');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('LAVADO INTERNO', '1.5', 'ACTIVIDAD');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('LAVADO EXTERNO', '2.0', 'ACTIVIDAD');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('CONTROLAR LA CALIDAD DE LAS REPARACIONES', '3', 'ACTIVIDAD');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('CAMBIO DE CUBIERTAS', '1.0', 'ACTIVIDAD');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('CAMIBIO DE LLANTAS', '1.0', 'ACTIVIDAD');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('CAMBIO DE FAROS', '1.0', 'ACTIVIDAD');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('REPARACION DEL TIMBRE', '1.5', 'ACTIVIDAD');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('MANTENIMIENTO DEL AC', '2.5', 'ACTIVIDAD');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('REPARACION DEL AC', '3.5', 'ACTIVIDAD');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('REVISIÓN TUBERÍAS Y MANGUERAS DEL SISTEMA NEUMÁTICO E HIDRÁULICO', '2.5', 'ACTIVIDAD');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('VERIFICACIÓN NIVEL DE COMBUSTIBLE, AGUA Y ACEITE', '3.0', 'ACTIVIDAD');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('CAMBIO FILTRO DE COMBUSTIBLE', '1.5', 'ACTIVIDAD');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('LIMPIAR Y APRETAR TERMINALES DE BATERÍA', '2.0', 'ACTIVIDAD');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('PURGAR EL TANQUE DE AIRE', '1.0', 'ACTIVIDAD');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('REVISIÓN DEL NIVEL Y VERIFICACIÓN DEL CIRCUITO DE REFRIGERANTE', '0.5', 'ACTIVIDAD');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('CAMBIO DE CADENA O CORREA DE REPARTICIÓN', '3.0', 'ACTIVIDAD');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('PINTURA DE PIEZA', '4.0', 'ACTIVIDAD');

insert into G_MIGRACION (DESCRIPCION, VALOR1, VALOR2)
values ('LLIMPIEZA DE INYECTORES, CUERPO DE ACELERACIÓN Y CONECTORES ELÉCTRICOS', '3.0', 'ACTIVIDAD');

COMMIT;
